import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

/**
 * Sidebars configuration for documentation.
 *
 * Uses autogenerated sidebars. The _category_.json files in each
 * subdirectory control ordering and labels.
 *
 * - docsSidebar: hand-authored product docs. Author under
 *   docs-site/docs/<section>/... (copied into docs-generated/docs/ by
 *   scripts/copy-product-docs.js on every build). Add a _category_.json
 *   per section folder. See docs-site/CONTENT-PLAN.md.
 * - specsSidebar / decisionsSidebar: generated Architecture section
 *   (OpenSpec specs + ADRs) -- do not hand-edit their content.
 */
const sidebars: SidebarsConfig = {
  docsSidebar: [
    {
      type: 'autogenerated',
      dirName: 'docs',
    },
    // Sidebar order: Getting Started (1), Features (2), Reference (3), and
    // Development (4) come from the autogenerated docs/ tree above (positions
    // set by each section's _category_.json); Architecture goes last and
    // points at the generated ADR/spec landing page (which links on to
    // /decisions and /specs — also in the navbar as ADRs / Specifications).
    {
      type: 'doc',
      id: 'index',
      label: 'Architecture',
    },
  ],
  specsSidebar: [
    {
      type: 'autogenerated',
      dirName: 'specs',
    },
  ],
  decisionsSidebar: [
    {
      type: 'autogenerated',
      dirName: 'decisions',
    },
  ],
};

export default sidebars;
